stages:
  - build
  - test
  - post-test

build:
  stage: build
  script:
    - mvn compile

unit-test:
  stage: test
  services:
    - name: registry.mouseover.fr:5000/bm/bingo-ifa/test-data
      alias: test-data
  variables:
    MYSQL_USER: "bingo-ifa"
    MYSQL_PASSWORD: "bingo-ifa"
    MYSQL_RANDOM_ROOT_PASSWORD: "yes"
  script:
    - mvn test
  artifacts:
    reports:
      junit:
        - target/surefire-reports/TEST-*.xml

coverage:
  stage: post-test
  coverage: '/Jacoco-Test-Coverage:(\d+\.?\d+)%/'
  script:
    - mvn jacoco:report
    - cat target/site/jacoco/index.html | grep -o 'Total[^%]*%' | sed -e 's/Total/Jacoco-Test-Coverage:/g'

dependencies:
  stage: post-test
  script:
    - mvn updateimpact:submit